apiVersion: v1
kind: Service
metadata:
  name: cement-copilot-api
  labels:
    app: cement-copilot-api
spec:
  selector:
    app: cement-copilot-api
  ports:
    - name: http
      port: 8000
      targetPort: http
